// Generated by gencpp from file slamware_ros_sdk/BasicSensorInfoArray.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_BASICSENSORINFOARRAY_H
#define SLAMWARE_ROS_SDK_MESSAGE_BASICSENSORINFOARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/BasicSensorInfo.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct BasicSensorInfoArray_
{
  typedef BasicSensorInfoArray_<ContainerAllocator> Type;

  BasicSensorInfoArray_()
    : sensors_info()  {
    }
  BasicSensorInfoArray_(const ContainerAllocator& _alloc)
    : sensors_info(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::slamware_ros_sdk::BasicSensorInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::slamware_ros_sdk::BasicSensorInfo_<ContainerAllocator> >> _sensors_info_type;
  _sensors_info_type sensors_info;





  typedef boost::shared_ptr< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> const> ConstPtr;

}; // struct BasicSensorInfoArray_

typedef ::slamware_ros_sdk::BasicSensorInfoArray_<std::allocator<void> > BasicSensorInfoArray;

typedef boost::shared_ptr< ::slamware_ros_sdk::BasicSensorInfoArray > BasicSensorInfoArrayPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::BasicSensorInfoArray const> BasicSensorInfoArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator2> & rhs)
{
  return lhs.sensors_info == rhs.sensors_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2091030b7ab5ae719573c70a4242996";
  }

  static const char* value(const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2091030b7ab5ae7ULL;
  static const uint64_t static_value2 = 0x19573c70a4242996ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/BasicSensorInfoArray";
  }

  static const char* value(const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"BasicSensorInfo[] sensors_info\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/BasicSensorInfo\n"
"\n"
"int32 id\n"
"SensorType sensor_type\n"
"ImpactType impact_type\n"
"geometry_msgs/Pose install_pose\n"
"float32 refresh_freq\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/SensorType\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 BUMPER=0\n"
"int8 CLIFF=1\n"
"int8 SONAR=2\n"
"int8 DEPTH_CAMERA=3\n"
"int8 WALL_SENSOR=4\n"
"int8 MAG_TAPE_DETECTOR=5\n"
"\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/ImpactType\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 DIGITAL=0\n"
"int8 ANALOG=1\n"
"\n"
"int8 type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensors_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicSensorInfoArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::BasicSensorInfoArray_<ContainerAllocator>& v)
  {
    s << indent << "sensors_info[]" << std::endl;
    for (size_t i = 0; i < v.sensors_info.size(); ++i)
    {
      s << indent << "  sensors_info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::slamware_ros_sdk::BasicSensorInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.sensors_info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_BASICSENSORINFOARRAY_H
