// Generated by gencpp from file slamware_ros_sdk/Line2DFlt32.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_LINE2DFLT32_H
#define SLAMWARE_ROS_SDK_MESSAGE_LINE2DFLT32_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/Vec2DFlt32.h>
#include <slamware_ros_sdk/Vec2DFlt32.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct Line2DFlt32_
{
  typedef Line2DFlt32_<ContainerAllocator> Type;

  Line2DFlt32_()
    : id(0)
    , start()
    , end()  {
    }
  Line2DFlt32_(const ContainerAllocator& _alloc)
    : id(0)
    , start(_alloc)
    , end(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef  ::slamware_ros_sdk::Vec2DFlt32_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::slamware_ros_sdk::Vec2DFlt32_<ContainerAllocator>  _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> const> ConstPtr;

}; // struct Line2DFlt32_

typedef ::slamware_ros_sdk::Line2DFlt32_<std::allocator<void> > Line2DFlt32;

typedef boost::shared_ptr< ::slamware_ros_sdk::Line2DFlt32 > Line2DFlt32Ptr;
typedef boost::shared_ptr< ::slamware_ros_sdk::Line2DFlt32 const> Line2DFlt32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fb32a1fe2c48724cf93b623d4a93c15";
  }

  static const char* value(const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fb32a1fe2c48724ULL;
  static const uint64_t static_value2 = 0xcf93b623d4a93c15ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/Line2DFlt32";
  }

  static const char* value(const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 id\n"
"Vec2DFlt32 start\n"
"Vec2DFlt32 end\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/Vec2DFlt32\n"
"\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Line2DFlt32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::Vec2DFlt32_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::Vec2DFlt32_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_LINE2DFLT32_H
