// Generated by gencpp from file slamware_ros_sdk/MapKind.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_MAPKIND_H
#define SLAMWARE_ROS_SDK_MESSAGE_MAPKIND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct MapKind_
{
  typedef MapKind_<ContainerAllocator> Type;

  MapKind_()
    : kind(0)  {
    }
  MapKind_(const ContainerAllocator& _alloc)
    : kind(0)  {
  (void)_alloc;
    }



   typedef int8_t _kind_type;
  _kind_type kind;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(EXPLORERMAP)
  #undef EXPLORERMAP
#endif
#if defined(_WIN32) && defined(SWEEPERMAP)
  #undef SWEEPERMAP
#endif
#if defined(_WIN32) && defined(UWBMAP)
  #undef UWBMAP
#endif
#if defined(_WIN32) && defined(SLAMMAP)
  #undef SLAMMAP
#endif
#if defined(_WIN32) && defined(LOCALSLAMMAP)
  #undef LOCALSLAMMAP
#endif

  enum {
    UNKNOWN = -1,
    EXPLORERMAP = 0,
    SWEEPERMAP = 1,
    UWBMAP = 2,
    SLAMMAP = 3,
    LOCALSLAMMAP = 4,
  };


  typedef boost::shared_ptr< ::slamware_ros_sdk::MapKind_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::MapKind_<ContainerAllocator> const> ConstPtr;

}; // struct MapKind_

typedef ::slamware_ros_sdk::MapKind_<std::allocator<void> > MapKind;

typedef boost::shared_ptr< ::slamware_ros_sdk::MapKind > MapKindPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::MapKind const> MapKindConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::MapKind_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::MapKind_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MapKind_<ContainerAllocator2> & rhs)
{
  return lhs.kind == rhs.kind;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::MapKind_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MapKind_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MapKind_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MapKind_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MapKind_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f669b590664c371d1174e6a57069c534";
  }

  static const char* value(const ::slamware_ros_sdk::MapKind_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf669b590664c371dULL;
  static const uint64_t static_value2 = 0x1174e6a57069c534ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/MapKind";
  }

  static const char* value(const ::slamware_ros_sdk::MapKind_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int8 UNKNOWN=-1\n"
"int8 EXPLORERMAP=0\n"
"int8 SWEEPERMAP=1\n"
"int8 UWBMAP=2\n"
"int8 SLAMMAP=3\n"
"int8 LOCALSLAMMAP=4\n"
"\n"
"int8 kind\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::MapKind_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kind);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapKind_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::MapKind_<ContainerAllocator>& v)
  {
    s << indent << "kind: ";
    Printer<int8_t>::stream(s, indent + "  ", v.kind);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_MAPKIND_H
