// Generated by gencpp from file slamware_ros_sdk/MoveByThetaRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_MOVEBYTHETAREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_MOVEBYTHETAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/MoveOptions.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct MoveByThetaRequest_
{
  typedef MoveByThetaRequest_<ContainerAllocator> Type;

  MoveByThetaRequest_()
    : theta(0.0)
    , options()  {
    }
  MoveByThetaRequest_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , options(_alloc)  {
  (void)_alloc;
    }



   typedef float _theta_type;
  _theta_type theta;

   typedef  ::slamware_ros_sdk::MoveOptions_<ContainerAllocator>  _options_type;
  _options_type options;





  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveByThetaRequest_

typedef ::slamware_ros_sdk::MoveByThetaRequest_<std::allocator<void> > MoveByThetaRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::MoveByThetaRequest > MoveByThetaRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::MoveByThetaRequest const> MoveByThetaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.options == rhs.options;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f4151e8ecd474b3a0e237c25b3dfbd7";
  }

  static const char* value(const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f4151e8ecd474b3ULL;
  static const uint64_t static_value2 = 0xa0e237c25b3dfbd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/MoveByThetaRequest";
  }

  static const char* value(const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 theta\n"
"MoveOptions options\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/MoveOptions\n"
"\n"
"MoveOptionFlag opt_flags\n"
"OptionalFlt64 speed_ratio\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/MoveOptionFlag\n"
"\n"
"uint32 NONE=0\n"
"uint32 APPENDING=1\n"
"uint32 MILESTONE=2\n"
"uint32 NO_SMOOTH=4\n"
"uint32 KEY_POINTS=8\n"
"uint32 PRECISE=16\n"
"uint32 WITH_YAW=32\n"
"uint32 RETURN_UNREACHABLE_DIRECTLY=64\n"
"uint32 KEY_POINTS_WITH_OA=128\n"
"\n"
"uint32 flags\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/OptionalFlt64\n"
"\n"
"bool is_valid\n"
"float64 value\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.options);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveByThetaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::MoveByThetaRequest_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "options: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >::stream(s, indent + "  ", v.options);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_MOVEBYTHETAREQUEST_H
