// Generated by gencpp from file slamware_ros_sdk/MoveLineRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_MOVELINEREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_MOVELINEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/ArtifactUsage.h>
#include <slamware_ros_sdk/Line2DFlt32.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct MoveLineRequest_
{
  typedef MoveLineRequest_<ContainerAllocator> Type;

  MoveLineRequest_()
    : usage()
    , line()  {
    }
  MoveLineRequest_(const ContainerAllocator& _alloc)
    : usage(_alloc)
    , line(_alloc)  {
  (void)_alloc;
    }



   typedef  ::slamware_ros_sdk::ArtifactUsage_<ContainerAllocator>  _usage_type;
  _usage_type usage;

   typedef  ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator>  _line_type;
  _line_type line;





  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLineRequest_

typedef ::slamware_ros_sdk::MoveLineRequest_<std::allocator<void> > MoveLineRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::MoveLineRequest > MoveLineRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::MoveLineRequest const> MoveLineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator2> & rhs)
{
  return lhs.usage == rhs.usage &&
    lhs.line == rhs.line;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cf38560b548912a4639543a301c6d6b";
  }

  static const char* value(const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cf38560b548912aULL;
  static const uint64_t static_value2 = 0x4639543a301c6d6bULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/MoveLineRequest";
  }

  static const char* value(const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"ArtifactUsage usage\n"
"Line2DFlt32 line\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/ArtifactUsage\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 VIRTUAL_WALL=0\n"
"int8 VIRTUAL_TRACK=1\n"
"\n"
"int8 usage\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/Line2DFlt32\n"
"\n"
"uint32 id\n"
"Vec2DFlt32 start\n"
"Vec2DFlt32 end\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/Vec2DFlt32\n"
"\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.usage);
      stream.next(m.line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::MoveLineRequest_<ContainerAllocator>& v)
  {
    s << indent << "usage: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::ArtifactUsage_<ContainerAllocator> >::stream(s, indent + "  ", v.usage);
    s << indent << "line: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::Line2DFlt32_<ContainerAllocator> >::stream(s, indent + "  ", v.line);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_MOVELINEREQUEST_H
