// Generated by gencpp from file slamware_ros_sdk/MoveOptions.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_MOVEOPTIONS_H
#define SLAMWARE_ROS_SDK_MESSAGE_MOVEOPTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/MoveOptionFlag.h>
#include <slamware_ros_sdk/OptionalFlt64.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct MoveOptions_
{
  typedef MoveOptions_<ContainerAllocator> Type;

  MoveOptions_()
    : opt_flags()
    , speed_ratio()  {
    }
  MoveOptions_(const ContainerAllocator& _alloc)
    : opt_flags(_alloc)
    , speed_ratio(_alloc)  {
  (void)_alloc;
    }



   typedef  ::slamware_ros_sdk::MoveOptionFlag_<ContainerAllocator>  _opt_flags_type;
  _opt_flags_type opt_flags;

   typedef  ::slamware_ros_sdk::OptionalFlt64_<ContainerAllocator>  _speed_ratio_type;
  _speed_ratio_type speed_ratio;





  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> const> ConstPtr;

}; // struct MoveOptions_

typedef ::slamware_ros_sdk::MoveOptions_<std::allocator<void> > MoveOptions;

typedef boost::shared_ptr< ::slamware_ros_sdk::MoveOptions > MoveOptionsPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::MoveOptions const> MoveOptionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator2> & rhs)
{
  return lhs.opt_flags == rhs.opt_flags &&
    lhs.speed_ratio == rhs.speed_ratio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e9be980ef594e7453a8d9bbbda54e01";
  }

  static const char* value(const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e9be980ef594e74ULL;
  static const uint64_t static_value2 = 0x53a8d9bbbda54e01ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/MoveOptions";
  }

  static const char* value(const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"MoveOptionFlag opt_flags\n"
"OptionalFlt64 speed_ratio\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/MoveOptionFlag\n"
"\n"
"uint32 NONE=0\n"
"uint32 APPENDING=1\n"
"uint32 MILESTONE=2\n"
"uint32 NO_SMOOTH=4\n"
"uint32 KEY_POINTS=8\n"
"uint32 PRECISE=16\n"
"uint32 WITH_YAW=32\n"
"uint32 RETURN_UNREACHABLE_DIRECTLY=64\n"
"uint32 KEY_POINTS_WITH_OA=128\n"
"\n"
"uint32 flags\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/OptionalFlt64\n"
"\n"
"bool is_valid\n"
"float64 value\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.opt_flags);
      stream.next(m.speed_ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveOptions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::MoveOptions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::MoveOptions_<ContainerAllocator>& v)
  {
    s << indent << "opt_flags: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::MoveOptionFlag_<ContainerAllocator> >::stream(s, indent + "  ", v.opt_flags);
    s << indent << "speed_ratio: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::OptionalFlt64_<ContainerAllocator> >::stream(s, indent + "  ", v.speed_ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_MOVEOPTIONS_H
