// Generated by gencpp from file slamware_ros_sdk/RecoverLocalizationRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_RECOVERLOCALIZATIONREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_RECOVERLOCALIZATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/RectFlt32.h>
#include <slamware_ros_sdk/LocalizationOptions.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct RecoverLocalizationRequest_
{
  typedef RecoverLocalizationRequest_<ContainerAllocator> Type;

  RecoverLocalizationRequest_()
    : area()
    , options()  {
    }
  RecoverLocalizationRequest_(const ContainerAllocator& _alloc)
    : area(_alloc)
    , options(_alloc)  {
  (void)_alloc;
    }



   typedef  ::slamware_ros_sdk::RectFlt32_<ContainerAllocator>  _area_type;
  _area_type area;

   typedef  ::slamware_ros_sdk::LocalizationOptions_<ContainerAllocator>  _options_type;
  _options_type options;





  typedef boost::shared_ptr< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecoverLocalizationRequest_

typedef ::slamware_ros_sdk::RecoverLocalizationRequest_<std::allocator<void> > RecoverLocalizationRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::RecoverLocalizationRequest > RecoverLocalizationRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::RecoverLocalizationRequest const> RecoverLocalizationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area &&
    lhs.options == rhs.options;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23b8ad43efcddaa451d7f46385bf8b37";
  }

  static const char* value(const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23b8ad43efcddaa4ULL;
  static const uint64_t static_value2 = 0x51d7f46385bf8b37ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/RecoverLocalizationRequest";
  }

  static const char* value(const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"RectFlt32 area\n"
"LocalizationOptions options\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/RectFlt32\n"
"\n"
"float32 x		# x of position\n"
"float32 y		# y of position\n"
"float32 w		# width\n"
"float32 h		# height\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/LocalizationOptions\n"
"\n"
"OptionalInt32 max_time_ms\n"
"OptionalLocalizationMovement mvmt_type\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/OptionalInt32\n"
"\n"
"bool is_valid\n"
"int32 value\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/OptionalLocalizationMovement\n"
"\n"
"bool is_valid\n"
"LocalizationMovement value\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/LocalizationMovement\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 NO_MOVE=0\n"
"int8 ROTATE_ONLY=1\n"
"int8 ANY=2\n"
"\n"
"int8 type\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
      stream.next(m.options);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecoverLocalizationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::RecoverLocalizationRequest_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::RectFlt32_<ContainerAllocator> >::stream(s, indent + "  ", v.area);
    s << indent << "options: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::LocalizationOptions_<ContainerAllocator> >::stream(s, indent + "  ", v.options);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_RECOVERLOCALIZATIONREQUEST_H
