// Generated by gencpp from file slamware_ros_sdk/RemoveLineRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_REMOVELINEREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_REMOVELINEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/ArtifactUsage.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct RemoveLineRequest_
{
  typedef RemoveLineRequest_<ContainerAllocator> Type;

  RemoveLineRequest_()
    : usage()
    , id(0)  {
    }
  RemoveLineRequest_(const ContainerAllocator& _alloc)
    : usage(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::slamware_ros_sdk::ArtifactUsage_<ContainerAllocator>  _usage_type;
  _usage_type usage;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveLineRequest_

typedef ::slamware_ros_sdk::RemoveLineRequest_<std::allocator<void> > RemoveLineRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::RemoveLineRequest > RemoveLineRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::RemoveLineRequest const> RemoveLineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator2> & rhs)
{
  return lhs.usage == rhs.usage &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "155e65283140a49f08b2e1d08d692dc4";
  }

  static const char* value(const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x155e65283140a49fULL;
  static const uint64_t static_value2 = 0x08b2e1d08d692dc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/RemoveLineRequest";
  }

  static const char* value(const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"ArtifactUsage usage\n"
"uint32 id\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/ArtifactUsage\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 VIRTUAL_WALL=0\n"
"int8 VIRTUAL_TRACK=1\n"
"\n"
"int8 usage\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.usage);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveLineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::RemoveLineRequest_<ContainerAllocator>& v)
  {
    s << indent << "usage: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::ArtifactUsage_<ContainerAllocator> >::stream(s, indent + "  ", v.usage);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_REMOVELINEREQUEST_H
