// Generated by gencpp from file slamware_ros_sdk/SetMapUpdateRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_SETMAPUPDATEREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_SETMAPUPDATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slamware_ros_sdk/MapKind.h>

namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct SetMapUpdateRequest_
{
  typedef SetMapUpdateRequest_<ContainerAllocator> Type;

  SetMapUpdateRequest_()
    : enabled(false)
    , kind()  {
    }
  SetMapUpdateRequest_(const ContainerAllocator& _alloc)
    : enabled(false)
    , kind(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef  ::slamware_ros_sdk::MapKind_<ContainerAllocator>  _kind_type;
  _kind_type kind;





  typedef boost::shared_ptr< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMapUpdateRequest_

typedef ::slamware_ros_sdk::SetMapUpdateRequest_<std::allocator<void> > SetMapUpdateRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::SetMapUpdateRequest > SetMapUpdateRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::SetMapUpdateRequest const> SetMapUpdateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enabled == rhs.enabled &&
    lhs.kind == rhs.kind;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c52ca05137725a8c1db88bf912fafeb8";
  }

  static const char* value(const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc52ca05137725a8cULL;
  static const uint64_t static_value2 = 0x1db88bf912fafeb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/SetMapUpdateRequest";
  }

  static const char* value(const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool enabled\n"
"MapKind kind\n"
"\n"
"================================================================================\n"
"MSG: slamware_ros_sdk/MapKind\n"
"\n"
"int8 UNKNOWN=-1\n"
"int8 EXPLORERMAP=0\n"
"int8 SWEEPERMAP=1\n"
"int8 UWBMAP=2\n"
"int8 SLAMMAP=3\n"
"int8 LOCALSLAMMAP=4\n"
"\n"
"int8 kind\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
      stream.next(m.kind);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMapUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::SetMapUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "kind: ";
    s << std::endl;
    Printer< ::slamware_ros_sdk::MapKind_<ContainerAllocator> >::stream(s, indent + "  ", v.kind);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_SETMAPUPDATEREQUEST_H
