// Generated by gencpp from file slamware_ros_sdk/SyncSetStcm.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCM_H
#define SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCM_H

#include <ros/service_traits.h>


#include <slamware_ros_sdk/SyncSetStcmRequest.h>
#include <slamware_ros_sdk/SyncSetStcmResponse.h>


namespace slamware_ros_sdk
{

struct SyncSetStcm
{

typedef SyncSetStcmRequest Request;
typedef SyncSetStcmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncSetStcm
} // namespace slamware_ros_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slamware_ros_sdk::SyncSetStcm > {
  static const char* value()
  {
    return "bf6e85150212bf18415ddb0faf371f8b";
  }

  static const char* value(const ::slamware_ros_sdk::SyncSetStcm&) { return value(); }
};

template<>
struct DataType< ::slamware_ros_sdk::SyncSetStcm > {
  static const char* value()
  {
    return "slamware_ros_sdk/SyncSetStcm";
  }

  static const char* value(const ::slamware_ros_sdk::SyncSetStcm&) { return value(); }
};


// service_traits::MD5Sum< ::slamware_ros_sdk::SyncSetStcmRequest> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::SyncSetStcm >
template<>
struct MD5Sum< ::slamware_ros_sdk::SyncSetStcmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::SyncSetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncSetStcmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::SyncSetStcmRequest> should match
// service_traits::DataType< ::slamware_ros_sdk::SyncSetStcm >
template<>
struct DataType< ::slamware_ros_sdk::SyncSetStcmRequest>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::SyncSetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncSetStcmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slamware_ros_sdk::SyncSetStcmResponse> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::SyncSetStcm >
template<>
struct MD5Sum< ::slamware_ros_sdk::SyncSetStcmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::SyncSetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncSetStcmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::SyncSetStcmResponse> should match
// service_traits::DataType< ::slamware_ros_sdk::SyncSetStcm >
template<>
struct DataType< ::slamware_ros_sdk::SyncSetStcmResponse>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::SyncSetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncSetStcmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCM_H
