// Generated by gencpp from file slamware_ros_sdk/SyncGetStcm.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_SYNCGETSTCM_H
#define SLAMWARE_ROS_SDK_MESSAGE_SYNCGETSTCM_H

#include <ros/service_traits.h>


#include <slamware_ros_sdk/SyncGetStcmRequest.h>
#include <slamware_ros_sdk/SyncGetStcmResponse.h>


namespace slamware_ros_sdk
{

struct SyncGetStcm
{

typedef SyncGetStcmRequest Request;
typedef SyncGetStcmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGetStcm
} // namespace slamware_ros_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slamware_ros_sdk::SyncGetStcm > {
  static const char* value()
  {
    return "8474031e9b4b9443bc35727251a73587";
  }

  static const char* value(const ::slamware_ros_sdk::SyncGetStcm&) { return value(); }
};

template<>
struct DataType< ::slamware_ros_sdk::SyncGetStcm > {
  static const char* value()
  {
    return "slamware_ros_sdk/SyncGetStcm";
  }

  static const char* value(const ::slamware_ros_sdk::SyncGetStcm&) { return value(); }
};


// service_traits::MD5Sum< ::slamware_ros_sdk::SyncGetStcmRequest> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::SyncGetStcm >
template<>
struct MD5Sum< ::slamware_ros_sdk::SyncGetStcmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::SyncGetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncGetStcmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::SyncGetStcmRequest> should match
// service_traits::DataType< ::slamware_ros_sdk::SyncGetStcm >
template<>
struct DataType< ::slamware_ros_sdk::SyncGetStcmRequest>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::SyncGetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncGetStcmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slamware_ros_sdk::SyncGetStcmResponse> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::SyncGetStcm >
template<>
struct MD5Sum< ::slamware_ros_sdk::SyncGetStcmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::SyncGetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncGetStcmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::SyncGetStcmResponse> should match
// service_traits::DataType< ::slamware_ros_sdk::SyncGetStcm >
template<>
struct DataType< ::slamware_ros_sdk::SyncGetStcmResponse>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::SyncGetStcm >::value();
  }
  static const char* value(const ::slamware_ros_sdk::SyncGetStcmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_SYNCGETSTCM_H
