(cl:in-package roborts_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GAME_TYPE-VAL
          GAME_TYPE
          GAME_PROGRESS-VAL
          GAME_PROGRESS
          SHOOTER_COOLING_RATE-VAL
          SHOOTER_COOLING_RATE
          SHOOTER_SPEED_LIMIT-VAL
          SHOOTER_SPEED_LIMIT
          SHOOTER_COOLING_LIMIT-VAL
          SHOOTER_COOLING_LIMIT
          ROBOT_ID-VAL
          ROBOT_ID
          REMAIN_HP-VAL
          REMAIN_HP
          MAX_HP-VAL
          MAX_HP
          ARMOR_ID-VAL
          ARMOR_ID
          HURT_TYPE-VAL
          HURT_TYPE
          BULLET_FREQ-VAL
          BULLET_FREQ
          BULLET_SPEED-VAL
          BULLET_SPEED
          BULLET_REMAINING_NUM-VAL
          BULLET_REMAINING_NUM
          KEY_BOARD-VAL
          KEY_BOARD
          OTHER_ROBOT_ID-VAL
          OTHER_ROBOT_ID
          TGX-VAL
          TGX
          TGY-VAL
          TGY
          TGZ-VAL
          TGZ
          BLUE_X-VAL
          BLUE_X
          BLUE_Y-VAL
          BLUE_Y
          BLUE_CONFIDEN-VAL
          BLUE_CONFIDEN
          RED_X-VAL
          RED_X
          RED_Y-VAL
          RED_Y
          RED_CONFIDEN-VAL
          RED_CONFIDEN
))