// Generated by gencpp from file roborts_msgs/PidPlannerStatusResponse.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUSRESPONSE_H
#define ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct PidPlannerStatusResponse_
{
  typedef PidPlannerStatusResponse_<ContainerAllocator> Type;

  PidPlannerStatusResponse_()
    : result(0)  {
    }
  PidPlannerStatusResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PidPlannerStatusResponse_

typedef ::roborts_msgs::PidPlannerStatusResponse_<std::allocator<void> > PidPlannerStatusResponse;

typedef boost::shared_ptr< ::roborts_msgs::PidPlannerStatusResponse > PidPlannerStatusResponsePtr;
typedef boost::shared_ptr< ::roborts_msgs::PidPlannerStatusResponse const> PidPlannerStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator1> & lhs, const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator1> & lhs, const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/PidPlannerStatusResponse";
  }

  static const char* value(const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PidPlannerStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::PidPlannerStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUSRESPONSE_H
