// Generated by gencpp from file roborts_msgs/PidPlannerStatus.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUS_H
#define ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUS_H

#include <ros/service_traits.h>


#include <roborts_msgs/PidPlannerStatusRequest.h>
#include <roborts_msgs/PidPlannerStatusResponse.h>


namespace roborts_msgs
{

struct PidPlannerStatus
{

typedef PidPlannerStatusRequest Request;
typedef PidPlannerStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PidPlannerStatus
} // namespace roborts_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roborts_msgs::PidPlannerStatus > {
  static const char* value()
  {
    return "a371bdf98ac23518e5ce8e1cbb0f1497";
  }

  static const char* value(const ::roborts_msgs::PidPlannerStatus&) { return value(); }
};

template<>
struct DataType< ::roborts_msgs::PidPlannerStatus > {
  static const char* value()
  {
    return "roborts_msgs/PidPlannerStatus";
  }

  static const char* value(const ::roborts_msgs::PidPlannerStatus&) { return value(); }
};


// service_traits::MD5Sum< ::roborts_msgs::PidPlannerStatusRequest> should match
// service_traits::MD5Sum< ::roborts_msgs::PidPlannerStatus >
template<>
struct MD5Sum< ::roborts_msgs::PidPlannerStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::PidPlannerStatus >::value();
  }
  static const char* value(const ::roborts_msgs::PidPlannerStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::PidPlannerStatusRequest> should match
// service_traits::DataType< ::roborts_msgs::PidPlannerStatus >
template<>
struct DataType< ::roborts_msgs::PidPlannerStatusRequest>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::PidPlannerStatus >::value();
  }
  static const char* value(const ::roborts_msgs::PidPlannerStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roborts_msgs::PidPlannerStatusResponse> should match
// service_traits::MD5Sum< ::roborts_msgs::PidPlannerStatus >
template<>
struct MD5Sum< ::roborts_msgs::PidPlannerStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roborts_msgs::PidPlannerStatus >::value();
  }
  static const char* value(const ::roborts_msgs::PidPlannerStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roborts_msgs::PidPlannerStatusResponse> should match
// service_traits::DataType< ::roborts_msgs::PidPlannerStatus >
template<>
struct DataType< ::roborts_msgs::PidPlannerStatusResponse>
{
  static const char* value()
  {
    return DataType< ::roborts_msgs::PidPlannerStatus >::value();
  }
  static const char* value(const ::roborts_msgs::PidPlannerStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_PIDPLANNERSTATUS_H
